### ISSUE TITLE
Problem with import FMU

### ISSUE THREAD

**Issue by andreidaian** [INTO-CPS-Association/into-cps-application#13]
I implemented a FMU using javaFMI framework. After the simulation start, I got the following error:
"Error: Setup Experiment failed {FMU}.FMUInstance did not successfully complete. It returned: Fatal".

The COE log is presented below:
WARN [NanoHttpd Request Processor (#22)] (CoeInitialize.scala:357) - Make sure the execution tool: '' is available during this simulation. 
DEBUG [NanoHttpd Request Processor (#23)] (NanoWebSocketImpl.java:26) - Opening web socket for session: 7b2779b0-01b0-40ea-85fe-98a6ea3057b2 
DEBUG [NanoHttpd Request Processor (#22)] (CoeSimulator.scala:68) - Calling setupExperiment for {FMU}.FMUInstance 
DEBUG [NanoHttpd Request Processor (#22)] (CoeSimulator.scala:676) - Calling freeInstance for: {FMU}.FMUInstance 
DEBUG [NanoHttpd Request Processor (#22)] (Fmu.java:117) - UnLoad FMU temp folder 
DEBUG [NanoHttpd Request Processor (#22)] (Fmu.java:123) - Deleting temp folder 
ERROR [NanoHttpd Request Processor (#22)] (RequestProcessors.java:354) - Error in simulation 
org.intocps.orchestration.coe.AbortSimulationException: Setup Experiment failed 
{FMU}.FMUInstance did not successfully complete. It returned: Fatal 
at org.intocps.orchestration.coe.scala.CoeObject$.handleCallResults(CoeObject.scala:117) 
at org.intocps.orchestration.coe.scala.CoeObject$.fmiCallAll(CoeObject.scala:99) 
at org.intocps.orchestration.coe.scala.CoeSimulator$.simulate(CoeSimulator.scala:66) 
at org.intocps.orchestration.coe.scala.Coe.simulate(Coe.scala:105) 
at org.intocps.orchestration.coe.httpserver.RequestProcessors.simulate(RequestProcessors.java:350) 
at org.intocps.orchestration.coe.httpserver.RequestProcessors.processSimulate(RequestProcessors.java:377) 
at org.intocps.orchestration.coe.httpserver.RequestHandler.simulate(RequestHandler.java:294) 
at org.intocps.orchestration.coe.httpserver.RequestHandler.handleRequest(RequestHandler.java:187) 
at org.intocps.orchestration.coe.httpserver.NanoWSDImpl.serveHttp(NanoWSDImpl.java:36) 
at fi.iki.elonen.NanoWSD.serve(NanoWSD.java:861) 
at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:927) 
at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:194) 
at java.lang.Thread.run(Unknown Source)

**Comment by CThuleHansen** [comment]
Hi,
Your FMU apparently returns fmi2Fatal, but I do not know why. Do you have any logging within the FMU?
Could you provide me with some information regarding Platform and Architecture? 

Have you tried running your FMU through the [FMU Compliance Checker](https://preview.fmi-standard.org/downloads/)?

**Comment by CThuleHansen** [comment]
@andreidaian any news on this? Otherwise closing in 5 days

**Comment by CThuleHansen** [comment]
Closing as no news
