### ISSUE TITLE
Github actions fails duing the build fase 

### ISSUE THREAD

**Issue by Unsongheroes** [INTO-CPS-Association/into-cps-application#137]
Compile-ts-uglify fails:

[10:47:27] 'compile-ts-uglify' errored after 9.01 s
[10:47:27] TypeScript error: /home/runner/work/into-cps-application/into-cps-application/node_modules/@types/fs-extra/index.d.ts(232,38): error TS2694: Namespace '"fs"' has no exported member 'BaseEncodingOptions'.
    at Object.getError (/home/runner/work/into-cps-application/into-cps-application/node_modules/gulp-typescript/release/utils.js:56:15)
    at Output.getError (/home/runner/work/into-cps-application/into-cps-application/node_modules/gulp-typescript/release/output.js:90:22)
    at Output.diagnostic (/home/runner/work/into-cps-application/into-cps-application/node_modules/gulp-typescript/release/output.js:93:25)
    at ProjectCompiler.reportDiagnostics (/home/runner/work/into-cps-application/into-cps-application/node_modules/gulp-typescript/release/compiler.js:147:33)
    at ProjectCompiler.inputDone (/home/runner/work/into-cps-application/into-cps-application/node_modules/gulp-typescript/release/compiler.js:43:38)
    at CompileStream.end (/home/runner/work/into-cps-application/into-cps-application/node_modules/gulp-typescript/release/project.js:136:31)
    at DestroyableTransform.onend (/home/runner/work/into-cps-application/into-cps-application/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:281:20)
    at DestroyableTransform.emit (events.js:198:15)
    at DestroyableTransform.EventEmitter.emit (domain.js:504:23)
    at endReadableNT (/home/runner/work/into-cps-application/into-cps-application/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
[10:47:27] 'prep-pkg' errored after 9.01 s
Error: Process completed with exit code 1.

**Comment by Unsongheroes** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/51521

**Comment by Unsongheroes** [comment]
Fixed the build process by downgrading the version of the types/fs to 9.0.7 the newest version of 9.0.8 has an issue with it typing.
