### ISSUE TITLE
Multi-model configuration does not get rendered

### ISSUE THREAD

**Issue by clagms** [INTO-CPS-Association/into-cps-application#214]
Steps to reproduce:
1. Open INTO-CPS-Application.4.0.5
2. Open the following project: [decoupled_model_cosim.zip](https://github.com/INTO-CPS-Association/into-cps-application/files/11755395/decoupled_model_cosim.zip)
3. Try to open the multi-model configuration.
4. Get a blank screen:
![image](https://github.com/INTO-CPS-Association/into-cps-application/assets/871103/8e75898a-9412-4960-b82b-5c06c09dc0d5)

This is a particularly nasty problem, as the user looses the multi-model configuration.

UPDATE: Some more investigation with the developer tools seems to point out at the problem source being the TestBench FMU.
When the INTO-CPS app contains that FMU, we get the following error:
```
C:\Users\D48113\AppData\Local\Temp\22YC1puCJ7fuv3E89xXES60huX8\resources\app.asar\dist\angular2-app\mm\mm-page.component.js:31 MMPAGECOMPONENT
@angular.js:2 Unhandled Promise rejection: Cannot read property 'hasAttributes' of null ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'hasAttributes' of null
    at t.populateFromModelDescription (C:\Users\D48113\AppData\Local\Temp\22YC1puCJ7fuv3E89xXES60huX8\resources\app.asar\dist\angular2-app\coe\models\Fmu.js:31)
    at C:\Users\D48113\AppData\Local\Temp\22YC1puCJ7fuv3E89xXES60huX8\resources\app.asar\dist\angular2-app\coe\models\Fmu.js:31
    at t.invoke (@angular.js:2)
    at e.run (@angular.js:2)
    at @angular.js:2
    at t.invokeTask (@angular.js:2)
    at e.runTask (@angular.js:2)
    at y (@angular.js:2)
    at e.invokeTask (@angular.js:2)
    at Immediate.i.useG.invoke (@angular.js:2) TypeError: Cannot read property 'hasAttributes' of null
    at t.populateFromModelDescription (C:\Users\D48113\AppData\Local\Temp\22YC1puCJ7fuv3E89xXES60huX8\resources\app.asar\dist\angular2-app\coe\models\Fmu.js:31:3858)
    at C:\Users\D48113\AppData\Local\Temp\22YC1puCJ7fuv3E89xXES60huX8\resources\app.asar\dist\angular2-app\coe\models\Fmu.js:31:2774
    at t.invoke (file:///C:/Users/D48113/AppData/Local/Temp/22YC1puCJ7fuv3E89xXES60huX8/resources/app.asar/dist/@angular.js:2:24060)
    at e.run (file:///C:/Users/D48113/AppData/Local/Temp/22YC1puCJ7fuv3E89xXES60huX8/resources/app.asar/dist/@angular.js:2:19259)
    at file:///C:/Users/D48113/AppData/Local/Temp/22YC1puCJ7fuv3E89xXES60huX8/resources/app.asar/dist/@angular.js:2:30742
    at t.invokeTask (file:///C:/Users/D48113/AppData/Local/Temp/22YC1puCJ7fuv3E89xXES60huX8/resources/app.asar/dist/@angular.js:2:24744)
    at e.runTask (file:///C:/Users/D48113/AppData/Local/Temp/22YC1puCJ7fuv3E89xXES60huX8/resources/app.asar/dist/@angular.js:2:19922)
    at y (file:///C:/Users/D48113/AppData/Local/Temp/22YC1puCJ7fuv3E89xXES60huX8/resources/app.asar/dist/@angular.js:2:27035)
    at e.invokeTask (file:///C:/Users/D48113/AppData/Local/Temp/22YC1puCJ7fuv3E89xXES60huX8/resources/app.asar/dist/@angular.js:2:25880)
    at Immediate.i.useG.invoke (file:///C:/Users/D48113/AppData/Local/Temp/22YC1puCJ7fuv3E89xXES60huX8/resources/app.asar/dist/@angular.js:2:25742)
Zone.__load_patch.r.onUnhandledError @ @angular.js:2
f @ @angular.js:2
t @ @angular.js:2
Zone.__load_patch.r.microtaskDrainDone @ @angular.js:2
y @ @angular.js:2
e.invokeTask @ @angular.js:2
i.useG.invoke @ @angular.js:2
n.args.<computed> @ @angular.js:2
processImmediate @ internal/timers.js:456
@angular.js:2 Unhandled Promise rejection: Cannot read property 'hasAttributes' of null ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'hasAttributes' of null
    at t.populateFromModelDescription (C:\Users\D48113\AppData\Local\Temp\22YC1puCJ7fuv3E89xXES60huX8\resources\app.asar\dist\angular2-app\coe\models\Fmu.js:31)
    at C:\Users\D48113\AppData\Local\Temp\22YC1puCJ7fuv3E89xXES60huX8\resources\app.asar\dist\angular2-app\coe\models\Fmu.js:31
    at t.invoke (@angular.js:2)
    at e.run (@angular.js:2)
    at @angular.js:2
    at t.invokeTask (@angular.js:2)
    at e.runTask (@angular.js:2)
    at y (@angular.js:2)
    at e.invokeTask (@angular.js:2)
    at Immediate.i.useG.invoke (@angular.js:2) TypeError: Cannot read property 'hasAttributes' of null
    at t.populateFromModelDescription (C:\Users\D48113\AppData\Local\Temp\22YC1puCJ7fuv3E89xXES60huX8\resources\app.asar\dist\angular2-app\coe\models\Fmu.js:31:3858)
    at C:\Users\D48113\AppData\Local\Temp\22YC1puCJ7fuv3E89xXES60huX8\resources\app.asar\dist\angular2-app\coe\models\Fmu.js:31:2774
    at t.invoke (file:///C:/Users/D48113/AppData/Local/Temp/22YC1puCJ7fuv3E89xXES60huX8/resources/app.asar/dist/@angular.js:2:24060)
    at e.run (file:///C:/Users/D48113/AppData/Local/Temp/22YC1puCJ7fuv3E89xXES60huX8/resources/app.asar/dist/@angular.js:2:19259)
    at file:///C:/Users/D48113/AppData/Local/Temp/22YC1puCJ7fuv3E89xXES60huX8/resources/app.asar/dist/@angular.js:2:30742
    at t.invokeTask (file:///C:/Users/D48113/AppData/Local/Temp/22YC1puCJ7fuv3E89xXES60huX8/resources/app.asar/dist/@angular.js:2:24744)
    at e.runTask (file:///C:/Users/D48113/AppData/Local/Temp/22YC1puCJ7fuv3E89xXES60huX8/resources/app.asar/dist/@angular.js:2:19922)
    at y (file:///C:/Users/D48113/AppData/Local/Temp/22YC1puCJ7fuv3E89xXES60huX8/resources/app.asar/dist/@angular.js:2:27035)
    at e.invokeTask (file:///C:/Users/D48113/AppData/Local/Temp/22YC1puCJ7fuv3E89xXES60huX8/resources/app.asar/dist/@angular.js:2:25880)
    at Immediate.i.useG.invoke (file:///C:/Users/D48113/AppData/Local/Temp/22YC1puCJ7fuv3E89xXES60huX8/resources/app.asar/dist/@angular.js:2:25742)
Zone.__load_patch.r.onUnhandledError @ @angular.js:2
f @ @angular.js:2
t @ @angular.js:2
Zone.__load_patch.r.microtaskDrainDone @ @angular.js:2
y @ @angular.js:2
e.invokeTask @ @angular.js:2
i.useG.invoke @ @angular.js:2
n.args.<computed> @ @angular.js:2
processImmediate @ internal/timers.js:456
```

**Comment by clagms** [comment]
@levisen this issue is pressing. Lectures and external tutorials are depending on this very basic functionality working.
I've asked @mapalmieri to try reproduce this issue as it could be just on my machine.
Thanks!
