### ISSUE TITLE
Setting application in developermode results in crash

### ISSUE THREAD

**Issue by Quanalogy** [INTO-CPS-Association/into-cps-application#63]
Using Fedora 29, java -version
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (build 1.8.0_201-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)

An uncaught Javascrip error:

"A JavaScript error occurred in the main process
Uncaught Exception:
Error: Attempting to call a function in a renderer windows that hasbeen closed or released. Function provided here:
DialogHandler.js:31:1094.
   a BrowserWindows.callIntoRenderer ($INTO-CPS-PATH/resources/electron.asar/browser/rpc-server.js:199:19)
  at emitOne (events.js:96:13)
  at BrowserWindow.emit(events.js:188:7)

**Comment by CThuleHansen** [comment]
I have a different version that I just build for linux.
It is uploaded in https://github.com/INTO-CPS-Association/into-cps-application/releases/tag/EXP-0.0.1
Could you try that?
