### ISSUE TITLE
Creating new FMU instance creatig crash

### ISSUE THREAD

**Issue by Quanalogy** [INTO-CPS-Association/into-cps-application#64]
Using Fedora 29, java -version
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (build 1.8.0_201-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)

The following stacktrace is shown in the developer console when adding FMU instance:

`Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
EXCEPTION: Error in angular2-app/mm/mm-configuration.component.html:12:49
EXCEPTION: Error in angular2-app/mm/mm-configuration.component.html:12:49
ORIGINAL EXCEPTION: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'
ORIGINAL STACKTRACE:
Error: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'
    at ExpressionChangedAfterItHasBeenCheckedException.BaseException [as constructor] (exceptions.ts:21)
    at new ExpressionChangedAfterItHasBeenCheckedException (exceptions.ts:47)
    at checkBinding (view_utils.ts:145)
    at DebugAppView._View_t4.detectChangesInternal (t.template.js:1104)
    at DebugAppView.AppView.detectChanges (view.ts:261)
    at DebugAppView.detectChanges (view.ts:377)
    at DebugAppView.AppView.detectContentChildrenChanges (view.ts:280)
    at DebugAppView._View_t2.detectChangesInternal (t.template.js:1007)
    at DebugAppView.AppView.detectChanges (view.ts:261)
    at DebugAppView.detectChanges (view.ts:377)
    at DebugAppView.AppView.detectContentChildrenChanges (view.ts:280)
    at DebugAppView._View_t0.detectChangesInternal (t.template.js:70)
    at DebugAppView.AppView.detectChanges (view.ts:261)
    at DebugAppView.detectChanges (view.ts:377)
    at DebugAppView.AppView.detectViewChildrenChanges (view.ts:288)
    at DebugAppView._View_e0.detectChangesInternal (e.template.js:134)
ERROR CONTEXT:
DebugContext {_view: _View_t4, _nodeIndex: 0, _tplRow: 12, _tplCol: 49}
Uncaught EXCEPTION: Error in angular2-app/mm/mm-configuration.component.html:12:49
ORIGINAL EXCEPTION: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'
ORIGINAL STACKTRACE:
Error: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'
    at ExpressionChangedAfterItHasBeenCheckedException.BaseException [as constructor] (/home/munk/Downloads/into-cps-app-3.4.6-linux-x64/resources/app/node_modules/@angular/core/src/facade/exceptions.js:27:23)
    at new ExpressionChangedAfterItHasBeenCheckedException (/home/munk/Downloads/into-cps-app-3.4.6-linux-x64/resources/app/node_modules/@angular/core/src/linker/exceptions.js:52:16)
    at checkBinding (/home/munk/Downloads/into-cps-app-3.4.6-linux-x64/resources/app/node_modules/@angular/core/src/linker/view_utils.js:133:19)
    at DebugAppView._View_t4.detectChangesInternal (t.template.js:1104:7)
    at DebugAppView.AppView.detectChanges (/home/munk/Downloads/into-cps-app-3.4.6-linux-x64/resources/app/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (/home/munk/Downloads/into-cps-app-3.4.6-linux-x64/resources/app/node_modules/@angular/core/src/linker/view.js:348:44)
    at DebugAppView.AppView.detectContentChildrenChanges (/home/munk/Downloads/into-cps-app-3.4.6-linux-x64/resources/app/node_modules/@angular/core/src/linker/view.js:261:19)
    at DebugAppView._View_t2.detectChangesInternal (t.template.js:1007:8)
    at DebugAppView.AppView.detectChanges (/home/munk/Downloads/into-cps-app-3.4.6-linux-x64/resources/app/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (/home/munk/Downloads/into-cps-app-3.4.6-linux-x64/resources/app/node_modules/@angular/core/src/linker/view.js:348:44)
    at DebugAppView.AppView.detectContentChildrenChanges (/home/munk/Downloads/into-cps-app-3.4.6-linux-x64/resources/app/node_modules/@angular/core/src/linker/view.js:261:19)
    at DebugAppView._View_t0.detectChangesInternal (t.template.js:70:8)
    at DebugAppView.AppView.detectChanges (/home/munk/Downloads/into-cps-app-3.4.6-linux-x64/resources/app/node_modules/@angular/core/src/linker/view.js:243:14)
    at DebugAppView.detectChanges (/home/munk/Downloads/into-cps-app-3.4.6-linux-x64/resources/app/node_modules/@angular/core/src/linker/view.js:348:44)
    at DebugAppView.AppView.detectViewChildrenChanges (/home/munk/Downloads/into-cps-app-3.4.6-linux-x64/resources/app/node_modules/@angular/core/src/linker/view.js:269:19)
    at DebugAppView._View_e0.detectChangesInternal (e.template.js:134:8)
ERROR CONTEXT:
[object Object]
`

**Comment by CThuleHansen** [comment]
I have a different version that I just build for linux.
It is uploaded in https://github.com/INTO-CPS-Association/into-cps-application/releases/tag/EXP-0.0.1
Could you try that?
