### ISSUE TITLE
Settings reading errors must not block the app.

### ISSUE THREAD

**Issue by idhugo** [INTO-CPS-Association/into-cps-application#88]
Npm start user data path: ~/.config/INTO-CPS APP
Failed to read settings from file: ~/.config/INTO-CPS APP/intoCpsApp/settings.json.
App threw an error during load
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Settings.load (/home/hdm/repos/into-cps/into-cps-application/dist/settings/settings.js:86:43)
    at new IntoCpsApp (/home/hdm/repos/into-cps/into-cps-application/dist/IntoCpsApp.js:64:23)
    at Object.<anonymous> (/home/hdm/repos/into-cps/into-cps-application/dist/main.js:44:18)
    at Object.<anonymous> (/home/hdm/repos/into-cps/into-cps-application/dist/main.js:157:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)

Workaround:

Delete contents in ~/.config/INTO-CPS APP

**Comment by Unsongheroes** [comment]
merged an update to the development branch, that should fix this error - see Commit hash: 3ed91d2ea11fd63cf8985451203875ca584c4691
